import path from "node:path";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "."),
    },
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup.ts"],
    include: [
      "lib/**/*.test.ts",
      "hooks/**/*.test.ts",
      "components/**/*.test.tsx",
      "app/api/**/*.test.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "lib/**/*.ts",
        "hooks/**/*.ts",
        "components/**/*.tsx",
        "app/api/**/*.ts",
      ],
      exclude: [
        "lib/**/*.test.ts",
        "hooks/**/*.test.ts",
        "components/**/*.test.tsx",
        "app/api/**/*.test.ts",
        "**/*.d.ts",
        // Type-only and static-data modules: nothing to branch on.
        "lib/github/types.ts",
        "lib/curated-categories.ts",
        // Barrel file - re-exports only, no logic of its own to cover.
        "lib/github/index.ts",
        // shadcn/radix primitives generated by the CLI, and the thin
        // wrappers around them: styling only, no logic of our own.
        "components/ui/**",
        "components/common/Tooltip.tsx",
        "components/providers/theme-provider.tsx",
        // Static loading skeletons: fixed markup, no props, no branches.
        "components/common/PackageCardSkeleton.tsx",
        "components/package/detail/PackageDetailSkeleton.tsx",
      ],
      thresholds: {
        lines: 90,
        statements: 90,
        functions: 88,
        branches: 80,
      },
    },
  },
});
